default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: DaxExchange_development

test:
  <<: *default
  database: DaxExchange_test
 
production:
  <<: *default
  database: DaxExchange_production
  username: DaxExchange
  password: <%= ENV['DAXEXCHANGE_DATABASE_PASSWORD'] %>
